services:
  rustwaf:
    build:
      context: ../kowalski
      dockerfile: compose/Dockerfile
    container_name: rust_waf
    restart: unless-stopped
    ports:
      - "8005:8000"
    depends_on:
      - redis
    environment:
      RUST_LOG: info
      REDIS_URL: redis://redis:6379
    volumes:
      - ../:/app
      - ./volumes/waf_data:/app/data

  redis:
    image: redis:7.4-alpine
    container_name: redis-waf
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
