services:
  postgres:
    image: postgres:16.3-alpine
    container_name: postgres-database_vul
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_EXTERNAL_PORT}:5432"

  # ADD TEST MAIL PROVIDER

  vulnerable-backend:
    build:
      context: ..
      dockerfile: compose/Dockerfile
    container_name: spring-backend_vul
    restart: unless-stopped
    volumes:
      - maven_cache:/root/.m2
    depends_on:
      - postgres
    ports:
      - "${BACKEND_PORT}:8000"
    env_file:
      - .env

volumes:
  postgres_data:
    driver: local
  maven_cache:
    driver: local
